### PR TITLE
Fix prosthesis debugger server 

### PR DESCRIPTION
**Pull request by rpl**
fix how prosthesis enable and start debugger server
(due to changes introduced by https://bugzilla.mozilla.org/show_bug.cgi?id=815522)
and "simulatorActor" exception on debugger server restart.

### CODE REVIEW

**Comment by rpl** [comment]
As a side effect of 5d176e8, during the first launch "devtools.debugger.remote-enabled" is undefined
so startDebugger will be called 1 time, but on any next launch "devtools.debugger.remote-enabled" 
will be already true and we set it to true anyway, then startDebugger will be called twice.

5207082 prevents race conditions due to this.

**Comment by rpl** [comment]
> I would use console.warn() here, since we don't expect it to happen.

console.warn causes a "side effect fail" during tests (it's a addon-sdk unit-test feature)

startDebugger it's called twice because when that setting is already true, settings listeners registered by b2g will be called twice.

we can workaround that using an option to suppress that warning during tests (but retain the log level until we found a working solution, I'm trying to get/set the setting but it's not working correctly).

**Comment by rpl** [comment]
or we can add this warning in a "known problems / test fails" list :-)

**Comment by rpl** [comment]
c774b4e seems to do the magic (get/set remote-tools.enabled)

**Comment by rpl** [comment]
My fault! I tested a lot of workarounds... and finally I picked the wrong one :-)
and I didn't notice that I forgot to dump the exception in the catch block :-(

thanks to your patch "patch-start-debugger.js" is much more cleaner!

**Comment by mykmelez** [comment]
Merged, thanks for the fix!

**Pull request merged**
