### PR TITLE
When clicking "Update" fetch manifest--don't rely on cache

### PR DESCRIPTION
**Pull request by breck7**

### CODE REVIEW

**Comment by mykmelez** [comment]
Thanks for the fix! I merged it with just two minor changes: added the upstream bug number to the comment and kept the _url_ field topmost.

**Comment by mykmelez** [comment]
And one more change: added you to the list of contributors! https://github.com/mozilla/r2d2b2g/commit/b7027dce1d13a47041bffe99c6273e82b9b70fa8

Thanks, Breck, I really appreciate that you not only reported the bug but also fixed it!

**Comment by breck7** [comment]
Awesome. Thanks! What's the release schedule like for the Simulator? I'm wondering how to track which version I'm using.

**Comment by mykmelez** [comment]
The schedule isn't consistent yet, but we're working on version 4 at the moment, and we intend to ship it at the end of this month or the beginning of the next month.

Between releases, we create preview builds every week or two, so you can generally stay up-to-date with development work by installing the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)). I'll next update the preview builds tomorrow (Tuesday) or Wednesday, which is when they'll acquire your fix!

**Comment by breck7** [comment]
Awesome. Thanks for the info!

**Pull request merged**
